---
# Now that we have their bindep, lets run bindep and find out
# what we have to install on this system
- name: run bindep to discover users's required pacakges
  shell: bindep -f ~{{ username }}/{{ item.name }}/{{ bindep_file }} | tail -1
  register: bindep_result
  ignore_errors: True

- name: run bindep to discover users's required pacakges
  shell: bindep -f ~{{ username }}/{{ item.name }}/{{ bindep_file }} -l newline
  register: bindep_list_result

- name: install list of packages
  package:
    name: "{{ pkg }}"
    state: present
  loop: "{{bindep_list_result.stdout_lines|flatten}}"
  loop_control:
    loop_var: pkg 
  when:
     -  bindep_result.stdout != ""
     -  ansible_os_family == "RedHat" or
        ansible_os_family == "Debian" or
        ansible_os_family == "Suse"

- name: install list of packages from bindep (MacOS)
  package:
     name: "{{ pkg }}"
     state: present
  loop:
     - "{{bindep_list_result.stdout_lines}}"
  loop_control:
    loop_var: pkg 
  become: False
  when:
     -  bindep_result.stdout != ""
     -  ansible_os_family == "Darwin"
