---
# Now that we have their bindep, lets run bindep and find out
# what we have to install on this system
- name: run bindep to discover users's required pacakges
  shell: bindep -f ~{{ username }}/{{ item.name }}/{{ bindep_file }}
  register: bindep_result
  ignore_errors: True

- name: run bindep to discover users's required pacakges
  shell: bindep -f ~{{ username }}/{{ item.name }}/{{ bindep_file }} -l newline
  register: bindep_list_result

- name: install list of packages
  package:
     name: "{{ item }}"
     state: present
  with_items:
     - "{{bindep_list_result.stdout_lines}}"
  when: >
      bindep_result.stdout != ""
