---
- name: install required MacOS dependencies
  become: True
  homebrew:
     name: "{{ macos_package_dependencies }}"
     state: present
  register: result
  until: result is succeeded
  when: macos_package_dependencies is defined

- name: install required suse python dependencies
  become: True
  pip:
     name: "{{ macos_python_dependencies }}"
     state: present
  register: result
  until: result is succeeded
  when: macos_python_dependencies is defined
