---
- name: install required suse dependencies
  become: True
  package:
     name: "{{ suse_package_dependencies }}"
     state: present
  register: result
  until: result is succeeded

- name: install required suse python dependencies
  become: True
  pip:
     name: "{{ suse_python_dependencies }}"
     state: present
  register: result
  until: result is succeeded
