---
- name: include_tasks install_on_suse.yml
  include_tasks: install_on_suse.yml
  when: ansible_os_family == "Suse"
  tags: package-install

- name: include_tasks install_on_ubuntu.yml
  include_tasks: install_on_ubuntu.yml
  when: ansible_os_family == "Debian"
  tags: package-install

- name: include_tasks install_on_redhat.yml
  include_tasks: install_on_redhat.yml
  when: ansible_os_family == "RedHat"
  tags: package-install

- name: include_tasks install_on_macos.yml
  include_tasks: install_on_macos.yml
  when: ansible_os_family == "Darwin"
  tags: package-install
